schema = 3

[mod]
  [mod."github.com/elmasy-com/randomip"]
    version = "v1.0.2"
    hash = "sha256-evULX434Fh03PLO28I+fQRsGfzOO1jlZ8Ac8egvjK/o="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.5.1"
    hash = "sha256-B8kZ8yiWgallT7R2j1kSRJcJkSGFVf9ise+TpXa+7XY="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.6"
    hash = "sha256-xToSfpuePctkTdhJtsuKIEkXwfMZbnkFT98ahIfd4wY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.4.3"
    hash = "sha256-2tuF/RgrEBKPYdfwTxvXATbylAlRkOxvUXNTXNo/NzM="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.4"
    hash = "sha256-R9u+VxearUE1fLLTcAoHTrV8ZhgE/KxXRNClmrfTLn0="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.0.0-beta.8"
    hash = "sha256-e6CwKHZtaNM1/Ru1wUTSiaMDimaLQcZUC/0nk3HEE+w="
  [mod."github.com/spf13/afero"]
    version = "v1.8.2"
    hash = "sha256-ERuG4GK1LOn72DRbT9URpo1QoVIm2A3mPtlf+xSPgx8="
  [mod."github.com/spf13/cast"]
    version = "v1.4.1"
    hash = "sha256-jaY+/RKUviKnE2h8Ly5cdZYinSE0uc32FW6+xfZ1Ghs="
  [mod."github.com/spf13/cobra"]
    version = "v1.4.0"
    hash = "sha256-I6j9sD61Ztcc2W/WGeWo3ggYtnGTxNxZ2EFPdtO0UEY="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.11.0"
    hash = "sha256-osI0G1j0KU6ZNIY+XA0qipK8v7ES0ReYHU3O+9Hz4Gg="
  [mod."github.com/subosito/gotenv"]
    version = "v1.2.0"
    hash = "sha256-RUsfBl9xvHk8H6SPwiLi/BpHjkyO/YLvlFmRfGRIW1U="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220412211240-33da011f77ad"
    hash = "sha256-/rLhQdPCfsSVS1Lgze1MpZBlf0XZed7TjcQpiI2n4OU="
  [mod."golang.org/x/text"]
    version = "v0.3.7"
    hash = "sha256-XH2pUzzQx95O0rak00grQvfACfL+EmZiV7ZzJBkX+XY="
  [mod."gopkg.in/ini.v1"]
    version = "v1.66.4"
    hash = "sha256-PZ5vwf47Pjv7lzaUlm/mIdkIfnwEpmSNYG1UIfGh3M4="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20210107192922-496545a6307b"
    hash = "sha256-j8yDji+vqsitpRZirpb4w/Em8nstgf28wpwkcrOlxBk="
